# Generated by Django 3.1.5 on 2021-02-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
    ]
