# Generated by Django 3.1.5 on 2021-02-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_location_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='pickup_location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
